export const UPDATE_PHOTOS = 'UPDATE_PHOTOS';
export const UPDATE_USER_PHOTOS = 'UPDATE_USER_PHOTOS';
export const UPDATE_USER = 'UPDATE_USER';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_MULTIPLE_TO_CART = 'ADD_MULTIPLE_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
export const TOGGLE_CART = 'TOGGLE_CART';
